---
title: "Customer Data Analysis"
output: rmarkdown::github_document
---
```{r Loading Custoemr Data}
# load customer data
customers <- read.csv("data/customer_info.csv")
```


```{r Customer Dimension Check, echo=TRUE, message=TRUE, warning=FALSE}
#Identify number of records
dim(customers)
```
```{r Customer Initil Data Summary, echo=TRUE, message=FALSE, warning=FALSE}
#view customer data
summary(customers)
```

```{r Cleaninf Customer data}
#Cleaning of Customer Data

#convert gender column type to factor
customers$gender <- factor(customers$gender)
#remove unwanted column
customers_clean <- customers[,c(2:4)]
```

```{r Cleaned Customer data summary}
#view summary of cleaned data
summary(customers_clean)
```

```{r View Customer head}
#view a subset of cleaned data
head(customers_clean)
```

```{r}
str(customers_clean)
```

```{r Loading product Data, message=FALSE, warning=FALSE}
# load product data
products <- read.csv("data/product_info.csv")
```

```{r Product Data Summary, message=FALSE, warning=FALSE}
#view products data
summary(products)
```

```{r Loading readr}
# Load the readr package
library(readr)
```


```{r Loading Cases Data, message=FALSE, warning=FALSE}
# load cases data
cases <- read.csv("data/customer_cases.csv")
```

```{r Cases Dimension Check, echo=TRUE}
#Identify number of records
dim(cases)
```

```{r Cases initial Data Summary, echo=TRUE, message=FALSE, warning=FALSE}
#view cases data summary
summary(cases)
```

```{r Loading Lubridate}
#seeing that date time comes in as character
# bring in lubridate to handle datetime
library(lubridate, warn.conflicts = FALSE)
```


```{r Cleaning cases Data}
#Cleaning of Cases Data

#remove unwanted column
cases_clean <- cases[,c(2:6)]

#convert reason & Channel column type to factor
cases_clean$reason <- factor(cases_clean$reason)
cases_clean$channel <- factor(cases_clean$channel)

#convert the date time column to datetime type
cases_clean$date_time <- ymd_hms(cases_clean$date_time)
```

```{r Final Cases summary}
#check the data types of cases data again
summary(cases_clean)
```

```{r Cases data type view}
str(cases_clean)
```

```{r Loading Customer Product Data, message=FALSE, warning=FALSE}
# load customer product data
customer_products <- read.csv("data/customer_product.csv")
```

```{r Customer Product Dimension Check, echo=TRUE, message=TRUE, warning=FALSE}
#Identify number of records
dim(customer_products)
```

```{r Customer Product Data Summary, echo=TRUE, message=FALSE, warning=FALSE}
#view cases data summary
summary(customer_products)
```

```{r Cleaning of Customer Product Data}
#Cleaning of Customer Product Data

#remove unwanted column
customer_product_clean <- customer_products[,c(2:5)]

#convert the date time column to datetime type
customer_product_clean$signup_date_time <- ymd_hms(customer_product_clean$signup_date_time)
customer_product_clean$cancel_date_time <- ymd_hms(customer_product_clean$cancel_date_time)
```

```{r Final Cleaning of Customer Product Data Summary, echo=TRUE, message=FALSE, warning=FALSE}
#view cases data summary
summary(customer_product_clean)
```

```{r Viewing of Customer Product Data type}
str(customer_product_clean)
```

```{r cleaned cusomer descriptive data}
#Descriptive Information
#Average age of customers based on gender
with(customers_clean, by(age, gender, mean))
```

```{r loadong ggplot}
#loading ggplot library
library(ggplot2)
```

```{r Plotting demographics, echo=TRUE, message=FALSE, warning=FALSE}
ggplot(customers_clean,aes(y=age, x=gender, fill=gender )) + geom_boxplot() + coord_flip()+ scale_fill_brewer(palette = "Set1")
```

```{r Renaming some columns}
#rename product column in customer_product to product_id
colnames(customer_product_clean)[2] <- "product_id"
#rename name column in product to subscription
colnames(products)[2] <- "subscription"
```

```{r Data Consolidation}
#combining data frames (customer product clean and products)
customer_consolidated_data = merge(x=customer_product_clean, y=products, by ="product_id", all.x = TRUE)
#combining data frames (customer consolidated data and customer data)
customer_consolidated_data = merge(x=customer_consolidated_data, y=customers_clean, by ="customer_id", all.x = TRUE)
head(customer_consolidated_data)
```

```{r viewing consolidated data summary}
summary(customer_consolidated_data)
```

```{r}
#duplicate dataframe for manipulation purpose
consolidated_modified <- customer_consolidated_data
```

```{r SignUp analytic breakdown}
#Signup analytic breakdown
consolidated_modified$yearIn <- strftime(consolidated_modified$signup_date_time, "%Y")
consolidated_modified$monthIn <- strftime(consolidated_modified$signup_date_time, "%h")
consolidated_modified$dayIn <- strftime(consolidated_modified$signup_date_time, "%d")
consolidated_modified$dayNameIn <- strftime(consolidated_modified$signup_date_time, "%a")
consolidated_modified$hourIn <- strftime(consolidated_modified$signup_date_time, "%H")
consolidated_modified$minuteIn <- strftime(consolidated_modified$signup_date_time, "%M")
consolidated_modified$AMPMIn <- strftime(consolidated_modified$signup_date_time, "%p")
```

```{r Cancel analytic breakdown}
#Signup analytic breakdown
consolidated_modified$yearOut <- strftime(consolidated_modified$cancel_date_time, "%Y")
consolidated_modified$monthOut <- strftime(consolidated_modified$cancel_date_time, "%h")
consolidated_modified$dayOut <- strftime(consolidated_modified$cancel_date_time, "%d")
consolidated_modified$dayNameOut <- strftime(consolidated_modified$cancel_date_time, "%a")
consolidated_modified$hourOut <- strftime(consolidated_modified$cancel_date_time, "%H")
consolidated_modified$minuteOut <- strftime(consolidated_modified$cancel_date_time, "%M")
consolidated_modified$AMPMOut <- strftime(consolidated_modified$cancel_date_time, "%p")
```

```{r}
str(consolidated_modified)
```
```{r}
str(consolidated_modified)
```


```{r}
#convert factorizable columns t factor
consolidated_modified$product_id <- factor(consolidated_modified$product_id)
consolidated_modified$subscription <- factor(consolidated_modified$subscription)
consolidated_modified$yearIn <- factor(consolidated_modified$yearIn)
consolidated_modified$yearOut <- factor(consolidated_modified$yearOut)
consolidated_modified$monthIn <- factor(consolidated_modified$monthIn)
consolidated_modified$monthOut <- factor(consolidated_modified$monthOut)
consolidated_modified$dayNameIn <- factor(consolidated_modified$dayNameIn)
consolidated_modified$dayNameOut <- factor(consolidated_modified$dayNameOut)
consolidated_modified$AMPMIn <- factor(consolidated_modified$AMPMIn)
consolidated_modified$AMPMOut <- factor(consolidated_modified$AMPMOut)
```

```{r}
#Creating dataframe for cancellations of suscriptions
consolidated_cancellation <- consolidated_modified
consolidated_cancellation <-na.omit(consolidated_cancellation)

head(consolidated_cancellation)
str(consolidated_cancellation)
summary(consolidated_cancellation)
```


```{r}
str(consolidated_modified)
```

```{r}
summary(consolidated_modified)
```

```{r}
install.packages("patchwork")
library(patchwork)
```

```{r}
summary(consolidated_modified$subscription)
summary(consolidated_modified$yearIn)
```


```{r}
plot1 <- ggplot(consolidated_modified,aes(x=subscription, fill=subscription)) + geom_bar(stat = "count")
plot2 <- ggplot(consolidated_modified,aes(x=yearIn)) + geom_bar(stat = "count")

plot1 + plot2
```

```{r}
plot3 <- ggplot(consolidated_modified,aes(x=subscription, fill=gender)) + geom_bar(stat = "count")
plot4 <- ggplot(consolidated_modified,aes(x=yearIn, fill=gender)) + geom_bar(stat = "count")
plot5 <- ggplot(consolidated_modified,aes(x=monthIn, fill=gender)) + geom_bar(stat = "count")
plot3 + plot4 + plot5
```

```{r message=FALSE, warning=FALSE}
library(cowplot)
```

```{r}
plot3 <- ggplot(consolidated_modified,aes(x=subscription, fill=gender)) + geom_bar(stat = "count")
plot4 <- ggplot(consolidated_modified,aes(x=yearIn, fill=gender)) + geom_bar(stat = "count")
plot5 <- ggplot(consolidated_modified,aes(x=monthIn, fill=gender)) + geom_bar(stat = "count")
plot_grid(plot3, plot4, plot5, labels = "AUTO")

```


```{r}
ggplot(consolidated_cancellation,aes(x=yearOut, fill= gender)) + geom_bar(stat = "count")
```

```{r}
ggplot(consolidated_modified,aes(x=monthIn, fill = gender)) + geom_bar(stat = "count") + coord_flip()
```
```{r}
ggplot(consolidated_cancellation,aes(x=monthOut, fill = gender)) + geom_bar(stat = "count") + coord_flip()
```

```{r}
ggplot(consolidated_modified,aes(x=yearIn)) + geom_bar(stat = "count") + ggtitle("Signup Annual Frequency")
```
```{r}
ggplot(consolidated_cancellation,aes(x=yearOut)) + geom_bar(stat = "count") + ggtitle("Cancellation Annual Frequency")
```


```{r}
ggplot(consolidated_modified,aes(x=monthIn, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Signup Monthly Frequency")
```
```{r}
ggplot(consolidated_cancellation,aes(x=monthOut, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Cancellation Monthly Frequency")
```


```{r}
ggplot(consolidated_modified,aes(x=dayNameIn, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Signup by Day of the Week")
```
```{r}
ggplot(consolidated_cancellation,aes(x=dayNameOut, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Cancellation by Day of the Week")
```

```{r}
ggplot(consolidated_modified,aes(x=dayIn, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Signup by Day of the Month")
```
```{r}
ggplot(consolidated_cancellation,aes(x=dayOut, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Cancellation by Day of the Month")
```

```{r}
ggplot(consolidated_modified,aes(x=hourIn, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Signup by Time of the Day")
```

```{r}
ggplot(consolidated_cancellation,aes(x=hourOut, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Cancellation by Time of the Day")
```
```{r}
ggplot(consolidated_modified,aes(x=AMPMIn, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Signup by Period of the Day")
```
```{r}
ggplot(consolidated_cancellation,aes(x=AMPMOut, fill=subscription)) + geom_bar(stat = "count") + ggtitle("Cancellation by Period of the Day")
```




```{r Loading Custoemr Data}
# load customer data
test_customers <- read.csv("data/customer_cases.csv", stringsAsFactors = TRUE)
str(test_customers)
```


```{r}
#create churn status column
consolidated_modified$churn <- ifelse(is.na(consolidated_modified$cancel_date_time),"No", "Yes")
```

```{r}
#convert churn column type to factor
consolidated_modified$churn <- factor(consolidated_modified$churn)
```

```{r}
str(consolidated_modified)
```

```{r}
#look at some characeristics
summary(consolidated_modified$subscription)
```

```{r}
#looking at the dependent variable (binary - Churn or not)
summary(consolidated_modified$churn)
```

```{r}
#isolating data fro tree classification
churn_data <- consolidated_modified[,c(5,8,9,10,11,12,13,14,15,16,24)]
str(churn_data)
```

```{r}
set.seed(427) #setting seed 
train_sample <- sample(508932, 480000)

#view train sample data type structure
str(train_sample)
```

```{r}
#splitting data for training and testing
churn_train <- churn_data[train_sample,] #training data
churn_test <- churn_data[-train_sample,] #test data
```

```{r}
# check the proportion of class variable
prop.table(summary(churn_train$churn))
prop.table(summary(churn_test$churn))
```

```{r}
#training a model on the data
#load C50 library
install.packages("C50")
library(C50)
```

```{r}
churn_model <- C5.0(churn_train[-11],churn_train$churn,control = C5.0Control(minCases = 200))

churn_model
```

#display detailed info about the tree
summary()
